In [6]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries imported successfully")

Libraries imported successfully

In [7]:
df = pd.read_csv("../data/raw/bank_churn.csv")

print("Dataset loaded successfully")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully
Rows: 10000
Columns: 14

In [8]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.1 MB

In [10]:
missing = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().mean() * 100).round(2)
})

missing.sort_values("Missing_Percentage", ascending=False)

                 Missing_Count  Missing_Percentage
RowNumber                    0                 0.0
CustomerId                   0                 0.0
Surname                      0                 0.0
CreditScore                  0                 0.0
Geography                    0                 0.0
Gender                       0                 0.0
Age                          0                 0.0
Tenure                       0                 0.0
Balance                      0                 0.0
NumOfProducts                0                 0.0
HasCrCard                    0                 0.0
IsActiveMember               0                 0.0
EstimatedSalary              0                 0.0
Exited                       0                 0.0

In [11]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [12]:
unique_values = pd.DataFrame({
    "Column": df.columns,
    "Unique_Values": [df[col].nunique() for col in df.columns]
})

unique_values

             Column  Unique_Values
0         RowNumber          10000
1        CustomerId          10000
2           Surname           2932
3       CreditScore            460
4         Geography              3
5            Gender              2
6               Age             70
7            Tenure             11
8           Balance           6382
9     NumOfProducts              4
10        HasCrCard              2
11   IsActiveMember              2
12  EstimatedSalary           9999
13           Exited              2

In [13]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
RowNumber,10000.0,5.000500e+03,2886.895680,1.00,2500.75,5.000500e+03,7.500250e+03,10000.00
CustomerId,10000.0,1.569094e+07,71936.186123,15565701.00,15628528.25,1.569074e+07,1.575323e+07,15815690.00
CreditScore,10000.0,6.505288e+02,96.653299,350.00,584.00,6.520000e+02,7.180000e+02,850.00
Age,10000.0,3.892180e+01,10.487806,18.00,32.00,3.700000e+01,4.400000e+01,92.00
Tenure,10000.0,5.012800e+00,2.892174,0.00,3.00,5.000000e+00,7.000000e+00,10.00
Balance,10000.0,7.648589e+04,62397.405202,0.00,0.00,9.719854e+04,1.276442e+05,250898.09
NumOfProducts,10000.0,1.530200e+00,0.581654,1.00,1.00,1.000000e+00,2.000000e+00,4.00
HasCrCard,10000.0,7.055000e-01,0.455840,0.00,0.00,1.000000e+00,1.000000e+00,1.00
IsActiveMember,10000.0,5.151000e-01,0.499797,0.00,0.00,1.000000e+00,1.000000e+00,1.00
EstimatedSalary,10000.0,1.000902e+05,57510.492818,11.58,51002.11,1.001939e+05,1.493882e+05,199992.48
Exited,10000.0,2.037000e-01,0.402769,0.00,0.00,0.000000e+00,0.000000e+00,1.00

In [14]:
categorical_columns = df.select_dtypes(include="object").columns

for col in categorical_columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- Surname ---
Surname
Smith        32
Scott        29
Martin       29
Walker       28
Brown        26
             ..
Salinas       1
Cleveland     1
Kashiwagi     1
Aldridge      1
Burbidge      1
Name: count, Length: 2932, dtype: int64

--- Geography ---
Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

--- Gender ---
Gender
Male      5457
Female    4543
Name: count, dtype: int64

C:\Users\roush\AppData\Local\Temp\ipykernel_24732\709346951.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include="object").columns

In [15]:
analysis_df = df.drop(
    columns=["RowNumber", "CustomerId", "Surname"]
).copy()

analysis_df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [16]:
analysis_df.shape

(10000, 11)

In [17]:
attrition_summary = (
    analysis_df["Exited"]
    .value_counts()
    .rename(index={0: "Existing Customer", 1: "Exited Customer"})
)

attrition_summary

Exited
Existing Customer    7963
Exited Customer      2037
Name: count, dtype: int64

In [18]:
attrition_rate = analysis_df["Exited"].mean() * 100

print(f"Customer Attrition Rate: {attrition_rate:.2f}%")

Customer Attrition Rate: 20.37%

In [19]:
categorical_cols = [
    "Geography",
    "Gender",
    "HasCrCard",
    "IsActiveMember",
    "NumOfProducts",
    "Exited"
]

for col in categorical_cols:
    print(f"\n--- {col} ---")
    print(analysis_df[col].value_counts())

--- Geography ---
Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

--- Gender ---
Gender
Male      5457
Female    4543
Name: count, dtype: int64

--- HasCrCard ---
HasCrCard
1    7055
0    2945
Name: count, dtype: int64

--- IsActiveMember ---
IsActiveMember
1    5151
0    4849
Name: count, dtype: int64

--- NumOfProducts ---
NumOfProducts
1    5084
2    4590
3     266
4      60
Name: count, dtype: int64

--- Exited ---
Exited
0    7963
1    2037
Name: count, dtype: int64

In [20]:
analysis_df["Geography"].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [21]:
analysis_df = df.drop(
    columns=["RowNumber", "CustomerId", "Surname"]
).copy()

print(analysis_df.shape)

(10000, 11)

In [22]:
attrition_summary = (
    analysis_df["Exited"]
    .value_counts()
    .rename(index={0: "Existing Customer", 1: "Exited Customer"})
)

attrition_summary

Exited
Existing Customer    7963
Exited Customer      2037
Name: count, dtype: int64

In [23]:
attrition_rate = analysis_df["Exited"].mean() * 100

print(f"Customer Attrition Rate: {attrition_rate:.2f}%")

Customer Attrition Rate: 20.37%

In [24]:
geography_summary = (
    analysis_df["Geography"]
    .value_counts()
    .reset_index()
)

geography_summary.columns = ["Geography", "Customers"]

geography_summary

  Geography  Customers
0    France       5014
1   Germany       2509
2     Spain       2477

In [25]:
gender_summary = (
    analysis_df["Gender"]
    .value_counts()
    .reset_index()
)

gender_summary.columns = ["Gender", "Customers"]

gender_summary

   Gender  Customers
0    Male       5457
1  Female       4543

In [26]:
print("Average Age:", round(analysis_df["Age"].mean(), 2))
print("Median Age:", analysis_df["Age"].median())
print("Minimum Age:", analysis_df["Age"].min())
print("Maximum Age:", analysis_df["Age"].max())

Average Age: 38.92
Median Age: 37.0
Minimum Age: 18
Maximum Age: 92

In [27]:
print("Average Credit Score:", round(analysis_df["CreditScore"].mean(), 2))
print("Median Credit Score:", analysis_df["CreditScore"].median())
print("Minimum Credit Score:", analysis_df["CreditScore"].min())
print("Maximum Credit Score:", analysis_df["CreditScore"].max())

Average Credit Score: 650.53
Median Credit Score: 652.0
Minimum Credit Score: 350
Maximum Credit Score: 850

In [28]:
analysis_df["Age_Group"] = pd.cut(
    analysis_df["Age"],
    bins=[17, 30, 40, 50, 60, 100],
    labels=["18-30", "31-40", "41-50", "51-60", "61+"]
)

analysis_df["Age_Group"].value_counts().sort_index()

Age_Group
18-30    1968
31-40    4451
41-50    2320
51-60     797
61+       464
Name: count, dtype: int64

In [29]:
analysis_df["CreditScore_Band"] = pd.cut(
    analysis_df["CreditScore"],
    bins=[349, 579, 669, 739, 799, 850],
    labels=[
        "Poor",
        "Fair",
        "Good",
        "Very Good",
        "Excellent"
    ]
)

analysis_df["CreditScore_Band"].value_counts().sort_index()

CreditScore_Band
Poor         2362
Fair         3331
Good         2428
Very Good    1224
Excellent     655
Name: count, dtype: int64

In [30]:
age_attrition = (
    analysis_df.groupby("Age_Group", observed=True)
    .agg(
        Customers=("Exited", "size"),
        Exited_Customers=("Exited", "sum"),
        Attrition_Rate=("Exited", "mean")
    )
    .reset_index()
)

age_attrition["Attrition_Rate"] = (
    age_attrition["Attrition_Rate"] * 100
).round(2)

age_attrition

  Age_Group  Customers  Exited_Customers  Attrition_Rate
0     18-30       1968               148            7.52
1     31-40       4451               538           12.09
2     41-50       2320               788           33.97
3     51-60        797               448           56.21
4       61+        464               115           24.78

In [31]:
credit_attrition = (
    analysis_df.groupby("CreditScore_Band", observed=True)
    .agg(
        Customers=("Exited", "size"),
        Exited_Customers=("Exited", "sum"),
        Attrition_Rate=("Exited", "mean")
    )
    .reset_index()
)

credit_attrition["Attrition_Rate"] = (
    credit_attrition["Attrition_Rate"] * 100
).round(2)

credit_attrition

  CreditScore_Band  Customers  Exited_Customers  Attrition_Rate
0             Poor       2362               520           22.02
1             Fair       3331               685           20.56
2             Good       2428               452           18.62
3        Very Good       1224               252           20.59
4        Excellent        655               128           19.54

In [32]:
geography_attrition = (
    analysis_df.groupby("Geography")
    .agg(
        Customers=("Exited", "size"),
        Exited_Customers=("Exited", "sum"),
        Attrition_Rate=("Exited", "mean")
    )
    .reset_index()
)

geography_attrition["Attrition_Rate"] = (
    geography_attrition["Attrition_Rate"] * 100
).round(2)

geography_attrition.sort_values("Attrition_Rate", ascending=False)

  Geography  Customers  Exited_Customers  Attrition_Rate
1   Germany       2509               814           32.44
2     Spain       2477               413           16.67
0    France       5014               810           16.15

In [33]:
gender_attrition = (
    analysis_df.groupby("Gender")
    .agg(
        Customers=("Exited", "size"),
        Exited_Customers=("Exited", "sum"),
        Attrition_Rate=("Exited", "mean")
    )
    .reset_index()
)

gender_attrition["Attrition_Rate"] = (
    gender_attrition["Attrition_Rate"] * 100
).round(2)

gender_attrition.sort_values("Attrition_Rate", ascending=False)

   Gender  Customers  Exited_Customers  Attrition_Rate
0  Female       4543              1139           25.07
1    Male       5457               898           16.46

In [34]:
activity_attrition = (
    analysis_df.groupby("IsActiveMember")
    .agg(
        Customers=("Exited", "size"),
        Exited_Customers=("Exited", "sum"),
        Attrition_Rate=("Exited", "mean")
    )
    .reset_index()
)

activity_attrition["Activity_Status"] = activity_attrition["IsActiveMember"].map({
    0: "Inactive",
    1: "Active"
})

activity_attrition["Attrition_Rate"] = (
    activity_attrition["Attrition_Rate"] * 100
).round(2)

activity_attrition[
    ["Activity_Status", "Customers", "Exited_Customers", "Attrition_Rate"]
]

  Activity_Status  Customers  Exited_Customers  Attrition_Rate
0        Inactive       4849              1302           26.85
1          Active       5151               735           14.27

In [35]:
product_attrition = (
    analysis_df.groupby("NumOfProducts")
    .agg(
        Customers=("Exited", "size"),
        Exited_Customers=("Exited", "sum"),
        Attrition_Rate=("Exited", "mean")
    )
    .reset_index()
)

product_attrition["Attrition_Rate"] = (
    product_attrition["Attrition_Rate"] * 100
).round(2)

product_attrition

   NumOfProducts  Customers  Exited_Customers  Attrition_Rate
0              1       5084              1409           27.71
1              2       4590               348            7.58
2              3        266               220           82.71
3              4         60                60          100.00

In [36]:
analysis_df["Balance_Segment"] = pd.cut(
    analysis_df["Balance"],
    bins=[-1, 1, 50000, 100000, 150000, float("inf")],
    labels=[
        "Zero Balance",
        "< 50K",
        "50K-100K",
        "100K-150K",
        "150K+"
    ]
)

balance_attrition = (
    analysis_df.groupby("Balance_Segment", observed=True)
    .agg(
        Customers=("Exited", "size"),
        Exited_Customers=("Exited", "sum"),
        Attrition_Rate=("Exited", "mean")
    )
    .reset_index()
)

balance_attrition["Attrition_Rate"] = (
    balance_attrition["Attrition_Rate"] * 100
).round(2)

balance_attrition

  Balance_Segment  Customers  Exited_Customers  Attrition_Rate
0    Zero Balance       3617               500           13.82
1           < 50K         75                26           34.67
2        50K-100K       1509               300           19.88
3       100K-150K       3830               987           25.77
4           150K+        969               224           23.12

In [37]:
tenure_attrition = (
    analysis_df.groupby("Tenure")
    .agg(
        Customers=("Exited", "size"),
        Exited_Customers=("Exited", "sum"),
        Attrition_Rate=("Exited", "mean")
    )
    .reset_index()
)

tenure_attrition["Attrition_Rate"] = (
    tenure_attrition["Attrition_Rate"] * 100
).round(2)

tenure_attrition

    Tenure  Customers  Exited_Customers  Attrition_Rate
0        0        413                95           23.00
1        1       1035               232           22.42
2        2       1048               201           19.18
3        3       1009               213           21.11
4        4        989               203           20.53
5        5       1012               209           20.65
6        6        967               196           20.27
7        7       1028               177           17.22
8        8       1025               197           19.22
9        9        984               213           21.65
10      10        490               101           20.61

In [38]:
geo_activity = (
    analysis_df.groupby(["Geography", "IsActiveMember"])
    .agg(
        Customers=("Exited", "size"),
        Exited_Customers=("Exited", "sum"),
        Attrition_Rate=("Exited", "mean")
    )
    .reset_index()
)

geo_activity["Activity_Status"] = geo_activity["IsActiveMember"].map({
    0: "Inactive",
    1: "Active"
})

geo_activity["Attrition_Rate"] = (
    geo_activity["Attrition_Rate"] * 100
).round(2)

geo_activity[
    ["Geography", "Activity_Status", "Customers",
     "Exited_Customers", "Attrition_Rate"]
].sort_values("Attrition_Rate", ascending=False)

  Geography Activity_Status  Customers  Exited_Customers  Attrition_Rate
2   Germany        Inactive       1261               518           41.08
3   Germany          Active       1248               296           23.72
4     Spain        Inactive       1165               272           23.35
0    France        Inactive       2423               512           21.13
1    France          Active       2591               298           11.50
5     Spain          Active       1312               141           10.75

In [39]:
from scipy.stats import chi2_contingency

In [40]:
def chi_square_test(df, feature, target="Exited"):
    contingency_table = pd.crosstab(df[feature], df[target])
    
    chi2, p_value, dof, expected = chi2_contingency(contingency_table)
    
    print(f"Feature: {feature}")
    print(f"Chi-square statistic: {chi2:.2f}")
    print(f"P-value: {p_value:.6f}")
    
    if p_value < 0.05:
        print("Result: Statistically significant association with attrition")
    else:
        print("Result: No statistically significant association with attrition")

In [41]:
chi_square_test(analysis_df, "Geography")

Feature: Geography
Chi-square statistic: 301.26
P-value: 0.000000
Result: Statistically significant association with attrition

In [42]:
chi_square_test(analysis_df, "Gender")

Feature: Gender
Chi-square statistic: 112.92
P-value: 0.000000
Result: Statistically significant association with attrition

In [43]:
chi_square_test(analysis_df, "IsActiveMember")

Feature: IsActiveMember
Chi-square statistic: 242.99
P-value: 0.000000
Result: Statistically significant association with attrition

In [44]:
chi_square_test(analysis_df, "NumOfProducts")

Feature: NumOfProducts
Chi-square statistic: 1503.63
P-value: 0.000000
Result: Statistically significant association with attrition

In [45]:
from scipy.stats import chi2_contingency

def cramers_v(df, feature, target="Exited"):
    table = pd.crosstab(df[feature], df[target])
    chi2, p_value, dof, expected = chi2_contingency(table)

    n = table.sum().sum()
    r, k = table.shape

    phi2 = chi2 / n
    phi2_corrected = max(0, phi2 - ((k - 1) * (r - 1)) / (n - 1))
    
    r_corrected = r - ((r - 1) ** 2) / (n - 1)
    k_corrected = k - ((k - 1) ** 2) / (n - 1)

    v = np.sqrt(
        phi2_corrected /
        min(k_corrected - 1, r_corrected - 1)
    )

    return v

In [46]:
features = [
    "Geography",
    "Gender",
    "IsActiveMember",
    "NumOfProducts"
]

results = []

for feature in features:
    results.append({
        "Feature": feature,
        "Cramers_V": round(cramers_v(analysis_df, feature), 3)
    })

effect_size = pd.DataFrame(results).sort_values(
    "Cramers_V",
    ascending=False
)

effect_size

          Feature  Cramers_V
3   NumOfProducts      0.387
0       Geography      0.173
2  IsActiveMember      0.156
1          Gender      0.106

In [47]:
kpi_summary = {
    "Total Customers": len(analysis_df),
    "Existing Customers": (analysis_df["Exited"] == 0).sum(),
    "Exited Customers": (analysis_df["Exited"] == 1).sum(),
    "Attrition Rate (%)": round(analysis_df["Exited"].mean() * 100, 2),
    "Average Age": round(analysis_df["Age"].mean(), 2),
    "Average Credit Score": round(analysis_df["CreditScore"].mean(), 2),
    "Average Balance": round(analysis_df["Balance"].mean(), 2),
    "Average Products": round(analysis_df["NumOfProducts"].mean(), 2),
    "Active Customer Rate (%)": round(
        analysis_df["IsActiveMember"].mean() * 100, 2
    )
}

kpi_summary_df = pd.DataFrame(
    kpi_summary.items(),
    columns=["KPI", "Value"]
)

kpi_summary_df

                        KPI     Value
0           Total Customers  10000.00
1        Existing Customers   7963.00
2          Exited Customers   2037.00
3        Attrition Rate (%)     20.37
4               Average Age     38.92
5      Average Credit Score    650.53
6           Average Balance  76485.89
7          Average Products      1.53
8  Active Customer Rate (%)     51.51

In [48]:
sql_df = analysis_df.drop(
    columns=["Age_Group", "CreditScore_Band", "Balance_Segment"],
    errors="ignore"
).copy()

sql_df.to_csv(
    "../data/processed/bank_customer_analysis.csv",
    index=False
)

print("SQL-ready dataset saved successfully")
print("Rows:", sql_df.shape[0])
print("Columns:", sql_df.shape[1])

OSError: Cannot save file into a non-existent directory: '..\data\processed'

In [49]:
import os

# Create the correct processed folder
os.makedirs("../data/processed", exist_ok=True)

# Save the SQL-ready dataset
sql_df = analysis_df.drop(
    columns=["Age_Group", "CreditScore_Band", "Balance_Segment"],
    errors="ignore"
).copy()

sql_df.to_csv(
    "../data/processed/bank_customer_analysis.csv",
    index=False
)

print("SQL-ready dataset saved successfully")
print("Rows:", sql_df.shape[0])
print("Columns:", sql_df.shape[1])

SQL-ready dataset saved successfully
Rows: 10000
Columns: 11